export const images = {
  panel: new URL('./assets/view-panel.svg', import.meta.url).href,
  console: new URL('./assets/view-console.svg', import.meta.url).href,
  parking: new URL('./assets/phase-parking.svg', import.meta.url).href,
  parkingRunning: new URL('./assets/phase-parking-running.svg', import.meta.url).href,
  taxiOut: new URL('./assets/phase-taxi-out.svg', import.meta.url).href,
  taxiOutRunning: new URL('./assets/phase-taxi-out-running.svg', import.meta.url).href,
  holding: new URL('./assets/phase-holding.svg', import.meta.url).href,
  holdingRunning: new URL('./assets/phase-holding-running.svg', import.meta.url).href,
  linedUp: new URL('./assets/phase-lined-up.svg', import.meta.url).href,
  linedUpRunning: new URL('./assets/phase-lined-up-running.svg', import.meta.url).href,
  departure: new URL('./assets/phase-departure.svg', import.meta.url).href,
  departureRunning: new URL('./assets/phase-departure-running.svg', import.meta.url).href,
  cruise: new URL('./assets/phase-cruise.svg', import.meta.url).href,
  cruiseRunning: new URL('./assets/phase-cruise-running.svg', import.meta.url).href,
  approach: new URL('./assets/phase-approach.svg', import.meta.url).href,
  approachRunning: new URL('./assets/phase-approach-running.svg', import.meta.url).href,
  landing: new URL('./assets/phase-landing.svg', import.meta.url).href,
  landingRunning: new URL('./assets/phase-landing-running.svg', import.meta.url).href,
  taxiIn: new URL('./assets/phase-taxi-in.svg', import.meta.url).href,
  taxiInRunning: new URL('./assets/phase-taxi-in-running.svg', import.meta.url).href,
  parkingSecuring: new URL('./assets/phase-parking-securing.svg', import.meta.url).href,
  parkingSecuringRunning: new URL('./assets/phase-parking-securing-running.svg', import.meta.url)
    .href,
} as const;
